### ISSUE TITLE
Not all MULT Obstructions showing

### ISSUE THREAD

**Issue by C-Rogge** [FireDynamics/fdsreader#55] opened 2023-01-03 13:16 UTC
Next one:

I created some obstructions with MULT-Lines, which show perfectly correct in SMV. Sadly, while collecting data with the fdsreader, only some of those seem to be recognized (similiar behavior to another issue of mine, #50).

In the original case 3/5 instances of the multiplied obstructions found their way in the fdsreader-data (the last 3), while in a simplified case ([fdsreaderTestcaseMultID.fds.txt](https://github.com/FireDynamics/fdsreader/files/10336821/fdsreaderTestcaseMultID.fds.txt)) the reader only found 1/5 objects (again the last one created).

**Comment by JanVogelsang** [comment] 2023-01-03 13:50
Hm, unfortunately I can't reproduce the error. When I run the simulation, all 5 obstructions get found and all have associated boundary data.

**Comment by C-Rogge** [comment] 2023-01-03 14:04
Ehm... Well, i can tho :D
I just tried it in a new script, literally just
_import fdsreader
sim = fdsreader.Simulation('CaseMult1')
print(sim.obstructions)_
and got the output
_ObstructionCollection([Obstruction(id=1, Bounding-Box=Extent([0.00, 0.20] x [0.80, 1.00] x [0.80, 1.00]), SubObstructions=1, Quantities=['AST'])])_

Which is still only one Obstruction, but this time the first one created. 
In my jupyter notebook the output, strangely enough, was 
_ObstructionCollection([Obstruction(id=1, Bounding-Box=Extent([0.80, 1.00] x [0.80, 1.00] x [0.80, 1.00]), SubObstructions=1, Quantities=['AST'])])_
But now, after rerunning fds, it also shows the first one created, just like the new script.

Im using Python 3.10.7, fdsreader 1.9.4 and FDS 6.7.9.

**Comment by JanVogelsang** [comment] 2023-01-03 14:10
Very strange, I am using the same FDS and fdsreader versions, just on Python3.9 (which should not change anything though).  

Could you try removing the .pickle file created by the fdsreader in the same directory as the .smv file? Maybe its just a caching issue.

**Comment by C-Rogge** [comment] 2023-01-03 14:13
Nope. Still the same output. I will try the case on another system and report back...

**Comment by JanVogelsang** [comment] 2023-01-03 14:24
I actually get the same result on 6.7.9, was testing on a new nightly build before, for which it worked strangely enough. Therefore, something in FDS changed which causes the fdsreader to get into trouble here.

**Comment by JanVogelsang** [comment] 2023-01-03 14:29
Ok it seems this will get fixed in the future when the actual obststruction IDs are written into the .smv file. For now there is nothing I can do about it, as there is simply not enough data output yet to reconstruct everything. I will upload a new version that works with the current nightly build which you can use until a new FDS version is out.

**Closed** 2023-01-03 14:33 UTC
